import { fileURLToPath } from 'node:url';

import { migrate } from 'drizzle-orm/postgres-js/migrator';

import { db } from './client.js';

// SQL migrations live in server/drizzle (generated by `npm run db:generate`).
// Resolve the folder relative to this file so it works from any cwd — at
// runtime this compiles to server/dist/db/migrate.js, so ../../drizzle.
const migrationsFolder = fileURLToPath(
  new URL('../../drizzle', import.meta.url),
);

/**
 * Apply pending schema migrations. App Platform dev databases are only
 * reachable from inside the app, so we migrate on boot rather than pushing
 * from a developer machine. Safe to run every start (no-op when up to date);
 * the service runs a single instance, so there's no migration race.
 */
export const runMigrations = async (): Promise<void> => {
  await migrate(db, { migrationsFolder });
  console.log('[db] migrations up to date');
};
