import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { client } from './client.js';

// SQL migrations live in server/drizzle (generated by `npm run db:generate`).
// Resolve relative to this file — at runtime it compiles to
// server/dist/db/migrate.js, so ../../drizzle -> server/drizzle.
const drizzleDir = fileURLToPath(new URL('../../drizzle', import.meta.url));

interface JournalEntry {
  idx: number;
  tag: string;
}

/**
 * Apply pending schema migrations at boot. We deliberately do NOT use Drizzle's
 * built-in migrator: it unconditionally runs `CREATE SCHEMA`, which requires
 * CREATE-on-database — a privilege App Platform dev-database users lack. This
 * runner keeps its bookkeeping table and all objects in the existing `public`
 * schema, so it only needs the ordinary CREATE-on-schema the DB owner has.
 *
 * Dev databases are only reachable from inside the app, so migrating on boot is
 * the only option. The service runs a single instance, so there's no race.
 */
export const runMigrations = async (): Promise<void> => {
  // TEMP diagnostics: identify what this bound DB role is actually allowed to do.
  const [ident] = await client<
    {
      current_user: string;
      current_database: string;
      search_path: string;
      db_create: boolean;
      public_create: boolean;
    }[]
  >`SELECT current_user,
           current_database() AS current_database,
           current_setting('search_path') AS search_path,
           has_database_privilege(current_database(), 'CREATE') AS db_create,
           has_schema_privilege('public', 'CREATE') AS public_create`;
  console.log(
    `[db] identity user=${ident.current_user} db=${ident.current_database} ` +
      `search_path=${ident.search_path} db_create=${ident.db_create} ` +
      `public_create=${ident.public_create}`,
  );
  const schemas = await client<{ nspname: string; owner: string }[]>`
    SELECT n.nspname, pg_get_userbyid(n.nspowner) AS owner
    FROM pg_namespace n
    WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname <> 'information_schema'`;
  console.log('[db] schemas:', JSON.stringify(schemas));
  try {
    await client.unsafe('CREATE SCHEMA IF NOT EXISTS "db"');
    console.log('[db] probe: CREATE SCHEMA "db" OK');
  } catch (e) {
    console.log('[db] probe: CREATE SCHEMA "db" FAILED:', (e as Error).message);
  }
  // END TEMP diagnostics

  await client.unsafe(
    `CREATE TABLE IF NOT EXISTS "_migrations" (
       "tag" text PRIMARY KEY,
       "applied_at" timestamptz NOT NULL DEFAULT now()
     )`,
  );

  const journal = JSON.parse(
    await readFile(`${drizzleDir}/meta/_journal.json`, 'utf8'),
  ) as { entries: JournalEntry[] };

  const appliedRows = await client<{ tag: string }[]>`SELECT tag FROM "_migrations"`;
  const applied = new Set(appliedRows.map((r) => r.tag));

  const pending = journal.entries
    .sort((a, b) => a.idx - b.idx)
    .filter((e) => !applied.has(e.tag));

  for (const entry of pending) {
    const sqlText = await readFile(`${drizzleDir}/${entry.tag}.sql`, 'utf8');
    const statements = sqlText
      .split('--> statement-breakpoint')
      .map((s) => s.trim())
      .filter(Boolean);

    await client.begin(async (tx) => {
      for (const statement of statements) {
        await tx.unsafe(statement);
      }
      await tx`INSERT INTO "_migrations" (tag) VALUES (${entry.tag})`;
    });
    console.log(`[db] applied migration ${entry.tag}`);
  }

  console.log(`[db] migrations up to date (${journal.entries.length} total)`);
};
